let s = "Knowledge of built-in JavaScript methods speeds up a tester's work";
console.log(s.charAt(0));
console.log(s.charAt(s.length - 1));
console.log(s.substring(1, 4));
console.log(s.substr(1, 3));
console.log(s.slice(1, 4));
console.log(s.slice(-3));
console.log(s.indexOf(1));
console.log(s.lastIndexOf('1'));
console.log(s.split());
console.log(s.replace('l', 'L')); 
console.log(s.replaceAll('l', 'L')); 
console.log(s.toUpperCase());
console.log(s.toLowerCase());
